Repository SOPT-all/36-COLLABORATION-SERVER-KB-STARBANKING, pull requests merged in 2025-05, with the labels that each got.

#4 Feat/#2 create entity
  src/main/java/org/sopt36th/seminar/domain/Contract.java
  src/main/java/org/sopt36th/seminar/domain/Deposit.java
  src/main/java/org/sopt36th/seminar/domain/enums/ContractState.java
Labels: ⭐ [FEAT], 🐑효은🐑

#8 Mod/#7 의존성 및 구조
  build.gradle
  src/main/java/org/sopt36th/seminar/common/entity/BaseEntity.java
  src/main/java/org/sopt36th/seminar/controller/ContractController.java
  src/main/java/org/sopt36th/seminar/repository/ContractRepository.java
  src/main/java/org/sopt36th/seminar/repository/DepositRepository.java
  src/main/java/org/sopt36th/seminar/repository/PreferentialRateRepository.java
  src/main/java/org/sopt36th/seminar/service/ContractService.java
  src/main/java/org/sopt36th/seminar/service/DepositService.java
  src/main/java/org/sopt36th/seminar/service/PreferentialService.java
  src/main/java/org/sopt36th/seminar/service/SavingService.java
Labels: ✅ [MOD], 🐑효은🐑

#13 [Feat/#6] 특정 적금 상세 조회 (거래 내역)
  src/main/java/org/sopt36th/seminar/SeminarApplication.java
  src/main/java/org/sopt36th/seminar/common/exception/GlobalErrorCode.java
  src/main/java/org/sopt36th/seminar/common/exception/GlobalExceptionHandler.java
  src/main/java/org/sopt36th/seminar/common/exception/custom/ContractNotFoundException.java
  src/main/java/org/sopt36th/seminar/common/response/message/SuccessMessage.java
  src/main/java/org/sopt36th/seminar/common/utils/DateUtil.java
  src/main/java/org/sopt36th/seminar/common/utils/RateUtil.java
  src/main/java/org/sopt36th/seminar/common/utils/TimeUtil.java
  src/main/java/org/sopt36th/seminar/controller/ContractController.java
  src/main/java/org/sopt36th/seminar/domain/Contract.java
  src/main/java/org/sopt36th/seminar/domain/Deposit.java
  src/main/java/org/sopt36th/seminar/domain/PreferentialRate.java
  src/main/java/org/sopt36th/seminar/domain/Saving.java
  src/main/java/org/sopt36th/seminar/domain/User.java
  src/main/java/org/sopt36th/seminar/dto/response/GetContractDetailResponse.java
  src/main/java/org/sopt36th/seminar/mapper/ContractMapper.java
  src/main/java/org/sopt36th/seminar/repository/ContractRepository.java
  src/main/java/org/sopt36th/seminar/repository/PreferentialRateRepository.java
  src/main/java/org/sopt36th/seminar/service/ContractService.java
Labels: ⭐ [FEAT], 🐑효은🐑

#18 [Feat/#16] 전체 계좌 조회
  src/main/java/org/sopt36th/seminar/controller/ContractController.java
  src/main/java/org/sopt36th/seminar/dto/response/AccountResponse.java
  src/main/java/org/sopt36th/seminar/dto/response/GetAllAccountsResponse.java
  src/main/java/org/sopt36th/seminar/mapper/ContractMapper.java
  src/main/java/org/sopt36th/seminar/service/ContractService.java
Labels: ⭐ [FEAT], 🍑소연🍑

#19 [Feat/#17] 계좌 이율 조회
  src/main/java/org/sopt36th/seminar/common/exception/custom/ContractNotFoundException.java
  src/main/java/org/sopt36th/seminar/common/response/message/SuccessMessage.java
  src/main/java/org/sopt36th/seminar/controller/ContractController.java
  src/main/java/org/sopt36th/seminar/domain/PreferentialRate.java
  src/main/java/org/sopt36th/seminar/dto/response/GetAccountRatesResponse.java
  src/main/java/org/sopt36th/seminar/dto/response/PreferentialRateResponse.java
  src/main/java/org/sopt36th/seminar/mapper/ContractMapper.java
  src/main/java/org/sopt36th/seminar/repository/PreferentialRateRepository.java
  src/main/java/org/sopt36th/seminar/service/ContractService.java
Labels: ⭐ [FEAT], 🍑소연🍑

#21 [Refactor/#20] swagger 코드 추가
  src/main/java/org/sopt36th/seminar/common/exception/BusinessException.java
  src/main/java/org/sopt36th/seminar/common/exception/GlobalExceptionHandler.java
  src/main/java/org/sopt36th/seminar/common/response/ApiResponse.java
  src/main/java/org/sopt36th/seminar/common/response/ErrorResponse.java
  src/main/java/org/sopt36th/seminar/common/utils/DateUtil.java
  src/main/java/org/sopt36th/seminar/controller/ContractController.java
  src/main/java/org/sopt36th/seminar/domain/Contract.java
  src/main/java/org/sopt36th/seminar/domain/Deposit.java
  src/main/java/org/sopt36th/seminar/domain/Saving.java
  src/main/java/org/sopt36th/seminar/domain/User.java
  src/main/java/org/sopt36th/seminar/domain/enums/ContractState.java
  src/main/java/org/sopt36th/seminar/dto/reqeust/tmp.txt
  src/main/java/org/sopt36th/seminar/dto/response/tmp.txt
  src/main/java/org/sopt36th/seminar/mapper/ContractStateMapper.java
  src/main/java/org/sopt36th/seminar/repository/ContractRepository.java
  src/main/java/org/sopt36th/seminar/repository/DepositRepository.java
  src/main/java/org/sopt36th/seminar/repository/PreferentialRateRepository.java
  src/main/java/org/sopt36th/seminar/repository/SavingRepository.java
  src/main/java/org/sopt36th/seminar/service/ContractService.java
  src/main/java/org/sopt36th/seminar/service/DepositService.java
  src/main/java/org/sopt36th/seminar/service/PreferentialService.java
  src/main/java/org/sopt36th/seminar/service/SavingService.java
Labels: ♻️ [REFACTOR], 🍑소연🍑
